# title: Just the Docs Template
# description: A starter template for a Jeykll site using the Just the Docs theme!
# theme: just-the-docs

# url: https://just-the-docs.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

title: Laboratorio Ecotroni - Regolamento d'uso e Documentazione
description: Regolamento d'uso e documentazione del Laboratorio Ecotroni del Dipartimento di Agraria Università degli Sutdi di Napoli Federico II
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
repository: mcrimaldi/ecotroni_docs # for github-metadata

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
